"""
Django settings for mysite project.

Generated by 'django-admin startproject' using Django 4.0.4.

For more information on this file, see
https://docs.djangoproject.com/en/4.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.0/ref/settings/
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get("SECRET_KEY",'')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

APPEND_SLASH=False

ALLOWED_HOSTS = ["*"]

# Media

if os.environ.get('RAILWAY_ENVIRONMENT'):
    MEDIA_ROOT = '/app/data'
else:
    # Local development path
    MEDIA_ROOT = os.path.join(BASE_DIR, 'data')

MEDIA_URL = '/data/'

# FORM SUBMISSION
# Comment out the following line and place your railway URL, and your production URL in the array.
# CSRF_TRUSTED_ORIGINS = ["https://web-production-e39f0.up.railway.app"]

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'analysis', 
    'rest_framework',
    'django_filters',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
]

ROOT_URLCONF = 'mysite.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'mysite.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.0/ref/settings/#databases

# os.environ.setdefault("PGDATABASE", "liftoff_dev")
# os.environ.setdefault("PGUSER", "username")
# os.environ.setdefault("PGPASSWORD", "")
# os.environ.setdefault("PGHOST", "localhost")
# os.environ.setdefault("PGPORT", "5432")


DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql_psycopg2',
        'NAME': os.environ.get("PGDATABASE",''),
        'USER': os.environ.get("PGUSER",''),
        'PASSWORD': os.environ.get("PGPASSWORD",''),
        'HOST': os.environ.get("PGHOST",''),
        'PORT': os.environ.get("PGPORT",''),
    }
}

# DATABASES={
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',  # Use the correct engine for SQLite
#         'NAME': BASE_DIR / 'db.sqlite3',         # Specify the path to your database file
#     }
# }

# Password validation
# https://docs.djangoproject.com/en/4.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True

PORT = int(os.environ.get('PORT', 8000))


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.0/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [os.path.join(BASE_DIR, "static")]
STATIC_ROOT = os.path.join(BASE_DIR, "staticfiles")

# Default primary key field type
# https://docs.djangoproject.com/en/4.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# ============ ADD THIS LOGGING CONFIGURATION ============
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'simple': {
            'format': '[{levelname}] {asctime} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'level': 'INFO',  # Changed from INFO to WARNING
            'class': 'logging.StreamHandler',
            'formatter': 'simple',
        },
        'file': {
            'level': 'INFO',
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': os.path.join(BASE_DIR, 'logs', 'app.log'),
            'maxBytes': 1024 * 1024 * 10,
            'backupCount': 5,
            'formatter': 'simple',
        },
    },
    'loggers': {
        'django': {
            'handlers': ['console', 'file'],
            'level': 'INFO',  # Changed from INFO
            'propagate': False,
        },
        'django.request': {
            'handlers': ['console', 'file'],
            'level': 'INFO',
            'propagate': False,
        },
        'django.db.backends': {
            'handlers': ['console', 'file'],
            'level': 'WARNING',  # Keep SQL queries at WARNING to reduce noise
            'propagate': False,
        },
        'analysis': {
            'handlers': ['console', 'file'],
            'level': 'INFO',  # Keep detailed logs for your app
            'propagate': False,
        },
        'celery': {
            'handlers': ['console', 'file'],
            'level': 'INFO',  # ✅ Show celery logs
            'propagate': False,
        },
        'celery.task': {
            'handlers': ['console', 'file'],
            'level': 'INFO',
            'propagate': False,
        },
    },
    'root': {
        'handlers': ['console', 'file'],
        'level': 'INFO',  # Changed from INFO
    },
}

# Create logs directory if it doesn't exist
LOGS_DIR = os.path.join(BASE_DIR, 'logs')
os.makedirs(LOGS_DIR, exist_ok=True)
# ============ END LOGGING CONFIGURATION ============

# Get Redis URL from environment
REDIS_URL = os.environ.get('REDIS_URL')

if not REDIS_URL:
    raise EnvironmentError("REDIS_URL environment variable is required")

print(f"📦 Django settings using Redis: {REDIS_URL[:60]}...")

# Celery broker and backend
CELERY_BROKER_URL = REDIS_URL
CELERY_RESULT_BACKEND = REDIS_URL

# Task configuration
CELERY_TASK_SOFT_TIME_LIMIT = 7200  # 2 hours
CELERY_TASK_TIME_LIMIT = 7500
CELERY_TASK_ACKS_LATE = True
CELERY_WORKER_PREFETCH_MULTIPLIER = 1
CELERY_TASK_REJECT_ON_WORKER_LOST = True

# Broker transport options
CELERY_BROKER_TRANSPORT_OPTIONS = {
    'visibility_timeout': 7200,
    'socket_keepalive': True,
}

# Result backend settings
CELERY_RESULT_EXPIRES = 3600

# Serialization
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_ACCEPT_CONTENT = ['json']

# Timezone
CELERY_TIMEZONE = 'UTC'
CELERY_ENABLE_UTC = True

# ⚠️ CRITICAL: Must be False in production!
CELERY_TASK_ALWAYS_EAGER = False
CELERY_TASK_EAGER_PROPAGATES = False

# # Task routing
# CELERY_TASK_ROUTES = {
#     'analysis.tasks.process_video_async': {
#         'queue': 'video_processing',
#     },
# }
# ============ END CELERY CONFIGURATION ============

# # Celery Configuration
# CELERY_TASK_SOFT_TIME_LIMIT = 900  # 10 minutes
# CELERY_TASK_TIME_LIMIT = 1200       # 15 minutes
# CELERY_TASK_ACKS_LATE = True
# CELERY_WORKER_PREFETCH_MULTIPLIER = 1
# CELERY_TASK_REJECT_ON_WORKER_LOST = True

# # For Redis broker
# CELERY_BROKER_TRANSPORT_OPTIONS = {
#     'visibility_timeout': 3600,  # 1 hour
#     'fanout_prefix': True,
#     'fanout_patterns': True
# }

# # Task routing for heavy AI workloads
# CELERY_TASK_ROUTES = {
#     'analysis.tasks.process_video_async': {
#         'queue': 'video_processing',
#         'routing_key': 'video_processing'
#     },
# }

# # Result backend settings
# CELERY_BROKER_URL = os.environ.get('REDIS_URL')
# CELERY_RESULT_BACKEND = os.environ.get('REDIS_URL')
# CELERY_RESULT_EXPIRES = 3600  # 1 hour

# # Task serialization
# CELERY_TASK_SERIALIZER = 'json'
# CELERY_RESULT_SERIALIZER = 'json'
# CELERY_ACCEPT_CONTENT = ['json']

# # Timezone
# CELERY_TIMEZONE = 'UTC'
# CELERY_ENABLE_UTC = True

# # Logging
# CELERY_WORKER_LOG_FORMAT = '[%(asctime)s: %(levelname)s/%(processName)s] %(message)s'
# CELERY_WORKER_TASK_LOG_FORMAT = '[%(asctime)s: %(levelname)s/%(processName)s][%(task_name)s(%(task_id)s)] %(message)s'

# # Security
# CELERY_TASK_ALWAYS_EAGER = False  # Set to True for development/testing
# CELERY_TASK_EAGER_PROPAGATES = False