# Generated by Django 5.1.3 on 2025-08-30 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('video_file', models.FileField(upload_to='videos/')),
                ('processed_video', models.FileField(blank=True, null=True, upload_to='processed_videos/')),
                ('video_data_json', models.FileField(blank=True, null=True, upload_to='video_data/')),
                ('sport_type', models.CharField(choices=[('tennis', 'Tennis'), ('running', 'Running'), ('soccer', 'Soccer')], help_text='Sport type selected by user', max_length=20)),
                ('analysis_status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('complete', 'Complete Analysis Available'), ('under_training', 'Sport Under Training'), ('failed', 'Analysis Failed')], default='pending', max_length=20)),
                ('overall_score', models.FloatField(blank=True, help_text='Overall technique score (0-10)', null=True)),
                ('detailed_scores', models.JSONField(blank=True, help_text='Detailed scores for different aspects', null=True)),
                ('frames_analyzed', models.IntegerField(blank=True, help_text='Number of frames with pose data', null=True)),
                ('feedback', models.TextField(blank=True, help_text='AI-generated coaching feedback', null=True)),
                ('shot_types_detected', models.JSONField(blank=True, help_text='List of detected shots/movements', null=True)),
                ('training_progress', models.CharField(blank=True, help_text='Training progress percentage', max_length=10, null=True)),
                ('estimated_completion', models.CharField(blank=True, help_text='Estimated completion date', max_length=20, null=True)),
                ('basic_metrics', models.JSONField(blank=True, help_text='Basic movement metrics captured', null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-uploaded_at'],
                'indexes': [models.Index(fields=['sport_type'], name='analysis_vi_sport_t_1d3fb2_idx'), models.Index(fields=['analysis_status'], name='analysis_vi_analysi_f218b1_idx'), models.Index(fields=['uploaded_at'], name='analysis_vi_uploade_7d9824_idx')],
            },
        ),
    ]
