# Generated by Django 5.0.6 on 2025-10-21 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='task_id',
            field=models.CharField(blank=True, help_text='Celery task ID for async processing', max_length=255, null=True),
        ),
    ]
